name: generate animation

on:
  # Executa automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *"
  
  # Permite executar manualmente o job a qualquer momento
  workflow_dispatch:
  
  # Executa a cada push no branch master
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Gera o jogo da cobrinha a partir do gráfico de contribuições do usuário do GitHub (pedrofratassi), gerando uma animação SVG em dist/github-contribution-grid-snake.svg
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: pedrofratassi
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Envia o conteúdo de dist para um branch
      # O conteúdo estará disponível em https://raw.githubusercontent.com/pedrofratassi/SEU_REPOSITORIO/output/github-contribution-grid-snake.svg ou como página do GitHub
      - name: push github-contribution-grid-snake.svg para o branch de saída
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
